### ISSUE TITLE
Replacement of other motors

### ISSUE THREAD

**Issue by XSJFYZS** [Annex-Engineering/Sherpa_Heavy-Extruder#1]
Hello
Thank you very much for your design and sharing
But this motor is difficult to buy, are there other alternatives?

**Comment by Annex-Engineering** [comment]
this design is only intended to use this motor. 

There are 10 motors in existence for this project, we plan on starting a group buy at some point in the next few months, however, we recommend you look at the sherpa mini, as its more appropriate for 99.9% of printers out there

**Comment by XSJFYZS** [comment]
I made a lot of changes to your mini
The entire gear set has moved 0.15mm to the left, making it easier to load the filament
In the original design, the gear obstructed the load filament
https://www.thingiverse.com/thing:4961936
